# Site
name: "Maker's Pet"
title: "Let's make awesome pet robots"
description: "Educational Pet Robots - built on Arduino, ROS2 and Kaia.ai"
logo: 'assets/images/logo.png'
favicon: 'favicon.ico'
baseurl: ''
google_analytics: 'G-3MP1M90FGZ'
disqus: 'makerspet-com'
mailchimp-list: 'https://remake.us4.list-manage.com/subscribe?u=ce7793379be11c5c705d99df0&id=62f859271b'
include: ["_pages"]
permalink: /blog/:title/
github_url: https://github.com/makerspet
youtube_url: https://youtube.com/@makerspet/
twitter_url: https://twitter.com/makerspet/
discord_url: https://discord.gg/UQt7ETWG
instagram_url: https://www.instagram.com/makerspet_com/
facebook_url: https://www.facebook.com/profile.php?id=61550661555594
facebook_group_url: https://www.facebook.com/groups/243730868651472/
reddit_group_url: https://www.reddit.com/r/3dPrintedHomeRobots/
mailchimp_signup_url: http://eepurl.com/gBV7tb
support_url: https://github.com/makerspet/support/discussions
privacy_policy_url: ./pages/privacy-policy
shipping_policy_url: ./pages/shipping-policy
terms_conditions_url: ./pages/terms-conditions
by: REMAKE AI
by_url: https://remake.ai

# safe: true

whitelist:
  - jekyll-redirect-from
  - jekyll-webp

# Authors
authors:
  marketing:
    name: REMAKE AI
    display_name: marketing
    avatar: 'assets/images/kaia_avatar.png'
#    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: marketing@makerspet.com
    web: https://remake.ai
    twitter: https://twitter.com/remakeai/
    description: "REMAKE AI"
  iliao:
    name: Ilia O.
    display_name: Ilia    
    avatar: 'assets/images/webp/ilia_avatar.webp'
    # gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: iliao@makerspet.com
    # web: https://www.wowthemes.net
    twitter: https://twitter.com/remakeai/
    description: "Hardware, software and startups 24/7"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-webp
  - jekyll-redirect-from

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/pages/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

webp:
  enabled: true
  
  # The quality of the webp conversion 0 to 100 (where 100 is least lossy)
  quality: 75

  # List of directories containing images to optimize, nested directories will only be checked if `nested` is true
  # By default the generator will search for a folder called `/img` under the site root and process all jpg, png and tiff image files found there.
  img_dir: ["assets/images"]

  # Whether to search in nested directories or not
  nested: false

  # add "".gif" to the format list to generate webp for animated gifs as well
  formats: [".jpeg", ".jpg", ".png", ".tiff"]

  # File extensions for animated gif files 
  gifs: [".gif"]

  # Set to true to always regenerate existing webp files
  regenerate: false

  # Local path to the WebP utilities to use (relative or absolute)
  # Omit or leave as nil to use the utilities shipped with the gem, override only to use your local install
  # Eg : "/usr/local/bin/cwebp"
  webp_path: nil

  # List of files or directories to exclude
  # e.g. custom or hand generated webp conversion files
  exclude: []

  # append '.webp' to filename after original extension rather than replacing it.
  # Default transforms `image.png` to `image.webp`, while changing to true transforms `image.png` to `image.png.webp`
  append_ext: false
